project_id = "ijxxjtiqitlyazwdqgwv"

[functions.inbound-email]
verify_jwt = false

[functions.create-client-account]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.create-agent]
verify_jwt = false

[functions.reset-client-password]
verify_jwt = false
