project_id = "ijxxjtiqitlyazwdqgwv"

[functions.inbound-email]
verify_jwt = false

[functions.create-client-account]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.create-agent]
verify_jwt = false

[functions.reset-client-password]
verify_jwt = false

[functions.fetch-inbound-emails]
verify_jwt = false

[functions.reply-email-ticket]
verify_jwt = false

[functions.download-attachment]
verify_jwt = false

[functions.gestaoclick-proxy]
verify_jwt = false

[functions.sync-delayed-orders]
verify_jwt = false

[functions.send-ticket-created-confirmation]
verify_jwt = false

[functions.handle-inbound-email-event-action]
verify_jwt = false

[functions.send-client-notification]
verify_jwt = false

[functions.letscall-sync-cdr]
verify_jwt = false

[functions.letscall-recording]
verify_jwt = false

[functions.letscall-originate-call]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.wms-delivery-assistance]
verify_jwt = false
